AplicacionNetRazor/Pages/Alumnos/Crear.cshtml.cs
using AplicacionNetRazor.Datos;
using AplicacionNetRazor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionNetRazor.Pages.Alumnos
{
    public class CrearModel : PageModel
    {
        private readonly AplicacionDBContext _contexto;

        public CrearModel(AplicacionDBContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty]
        public Alumno Alumno { get; set; }

        [TempData]
        public string Mensaje { get; set; }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _contexto.Add(Alumno);
            await _contexto.SaveChangesAsync();
            Mensaje = "Alumno creado exitosamente";
            return RedirectToPage("Index");
        }
        public void OnGet()
        {
        }
    }
}

AplicacionNetRazor/Pages/Alumnos/Editar.cshtml.cs
using AplicacionNetRazor.Datos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionNetRazor.Pages.Alumnos
{
    public class EditarModel : PageModel
    {
        private readonly AplicacionDBContext _contexto;
        public EditarModel(AplicacionDBContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty]
        public Modelos.Alumno Alumno { get; set; }

        [TempData]
        public string Mensaje { get; set; }
        public async Task OnGet(int id)
        {
            Alumno = await _contexto.Alumno.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var AlumnoDesdeBD = await _contexto.Alumno.FindAsync(Alumno.IdAlumno);

                AlumnoDesdeBD.Nombre = Alumno.Nombre;
                AlumnoDesdeBD.Apellido = Alumno.Apellido;
                AlumnoDesdeBD.Fecha_ing = Alumno.Fecha_ing;
                AlumnoDesdeBD.Hora_ing = Alumno.Hora_ing;
                AlumnoDesdeBD.Fecha_nac = Alumno.Fecha_nac;
                AlumnoDesdeBD.Cant_cursos = Alumno.Cant_cursos;
                AlumnoDesdeBD.Fecha_egr = Alumno.Fecha_egr;

                _contexto.SaveChangesAsync();
                Mensaje = "Alumno actualizado exitosamente";
                return RedirectToPage("Index");
            }

            return RedirectToPage("");

        }
    }
}

AplicacionNetRazor/Pages/Cursos/Crear.cshtml.cs
using AplicacionNetRazor.Datos;
using AplicacionNetRazor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionNetRazor.Pages.Cursos
{
    public class CrearModel : PageModel
    {
        private readonly AplicacionDBContext _contexto;

        public CrearModel(AplicacionDBContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty]
        public Curso Curso { get; set; }

        [TempData]
        public string Mensaje { get; set; }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Curso.FechaCreacion = DateTime.Now;

            _contexto.Add(Curso);
            await _contexto.SaveChangesAsync();
            Mensaje = "Curso creado exitosamente";
            return RedirectToPage("Index");
        }
        public void OnGet()
        {
        }


    }
}

AplicacionNetRazor/Pages/Cursos/Editar.cshtml.cs
using AplicacionNetRazor.Datos;
using AplicacionNetRazor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionNetRazor.Pages.Cursos
{
    public class EditarModel : PageModel
    {
        private readonly AplicacionDBContext _contexto;

        public EditarModel(AplicacionDBContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty]
        public Curso Curso { get; set; }

        [TempData]
        public string Mensaje { get; set; }
        public async Task OnGet(int id)
        {
            Curso = await _contexto.Curso.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var CursoDesdeBD = await _contexto.Curso.FindAsync(Curso.Id);

                CursoDesdeBD.NombreCurso = Curso.NombreCurso;
                CursoDesdeBD.CantidadClases = Curso.CantidadClases;
                CursoDesdeBD.Precio = Curso.Precio;

                _contexto.SaveChangesAsync();
                Mensaje = "Curso actualizado exitosamente";
                return RedirectToPage("Index"); 
            }

            return RedirectToPage("");

        }
    }
}

AplicacionNetRazor/Pages/Cursos/Index.cshtml.cs
using AplicacionNetRazor.Datos;
using AplicacionNetRazor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace AplicacionNetRazor.Pages.Cursos
{
    public class IndexModel : PageModel
    {
        private readonly AplicacionDBContext _contexto;

        public IndexModel(AplicacionDBContext contexto) 
        {
            _contexto = contexto;
        }

        public IEnumerable<Curso> Cursos { get; set; }

        [TempData]
        public string Mensaje { get; set; }
        public async Task OnGet()
        {
            Cursos = await _contexto.Curso.ToListAsync();
        }

        public async Task<IActionResult> OnPostBorrar(int id)
        {
            if (ModelState.IsValid)
            {
                var CursoBorrar = await _contexto.Curso.FindAsync(id);

                if (CursoBorrar == null)
                {
                    return NotFound();
                }

                _contexto.Curso.Remove(CursoBorrar);
                await _contexto.SaveChangesAsync();
                Mensaje = "Curso eliminado exitosamente";
                return RedirectToPage("Index");
            }

            return RedirectToPage("");

        }
    }
}

AplicacionNetRazor/Pages/Profesores/Crear.cshtml.cs
using AplicacionNetRazor.Datos;
using AplicacionNetRazor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionNetRazor.Pages.Profesores
{
    public class CrearModel : PageModel
    {
        private readonly AplicacionDBContext _contexto;

        public CrearModel(AplicacionDBContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty]
        public Profesor Profesor { get; set; }

        [TempData]
        public string Mensaje { get; set; }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _contexto.Add(Profesor);
            await _contexto.SaveChangesAsync();
            Mensaje = "Profesor creado exitosamente";
            return RedirectToPage("Index");
        }
        public void OnGet()
        {
        }
    }
}

AplicacionNetRazor/Pages/Profesores/Editar.cshtml.cs
using AplicacionNetRazor.Datos;
using AplicacionNetRazor.Modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionNetRazor.Pages.Profesores
{
    public class EditarModel : PageModel
    {
        private readonly AplicacionDBContext _contexto;
        public EditarModel(AplicacionDBContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty]
        public Profesor Profesor { get; set; }

        [TempData]
        public string Mensaje { get; set; }
        public async Task OnGet(int id)
        {
            Profesor = await _contexto.Profesor.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var ProfesorDesdeBD = await _contexto.Profesor.FindAsync(Profesor.idProf);

                ProfesorDesdeBD.Nombre = Profesor.Nombre;
                ProfesorDesdeBD.Apellido = Profesor.Apellido;
                ProfesorDesdeBD.Esp = Profesor.Esp;
                ProfesorDesdeBD.Fecha_ing = Profesor.Fecha_ing;
                ProfesorDesdeBD.Fecha_nac = Profesor.Fecha_nac;

                _contexto.SaveChangesAsync();
                Mensaje = "Profesor actualizado exitosamente";
                return RedirectToPage("Index");
            }

            return RedirectToPage("");

        }
    }
}

AplicacionNetRazor/Pages/Cursos/Crear.cshtml
@page
@model AplicacionNetRazor.Pages.Cursos.CrearModel
@{
    ViewData["Title"] = "Crear nuevo curso";
}

<div class="card">
    <div class="card-header">
        <h2 class="text-info">Lista de cursos</h2>  
    </div>
    <div class="card-body">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="container" style="padding:30px">
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.NombreCurso"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.NombreCurso" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.NombreCurso" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.CantidadClases"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.CantidadClases" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.CantidadClases" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.Precio"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.Precio" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.Precio" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2 offset-sm-2">
                            <input type="submit" value="Crear" class="btn btn-primary form-control" />
                        </div>
                        <div class="col-sm-4">
                            <a asp-page="Index" class="btn btn-success form-control">Volver a lista</a>
                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>

AplicacionNetRazor/Pages/Cursos/Editar.cshtml
@page
@model AplicacionNetRazor.Pages.Cursos.EditarModel
@{
    ViewData["Title"] = "Editar curso";
}

<div class="card">
    <div class="card-header">
        <h2 class="text-info">Lista de cursos</h2>  
    </div>
    <div class="card-body">
        <form method="post">

            <input type="hidden" asp-for="Curso.Id" />

            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="container" style="padding:30px">
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.NombreCurso"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.NombreCurso" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.NombreCurso" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.CantidadClases"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.CantidadClases" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.CantidadClases" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2">
                            <label asp-for="Curso.Precio"></label>
                        </div>
                        <div class="col-sm-6">
                            <input asp-for="Curso.Precio" class="form-control" />
                        </div>
                        <span asp-validation-for="Curso.Precio" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-2 offset-sm-2">
                            <input type="submit" value="Editar" class="btn btn-primary form-control" />
                        </div>
                        <div class="col-sm-4">
                            <a asp-page="Index" class="btn btn-success form-control">Volver a lista</a>
                        </div>
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>

AplicacionNetRazor/Pages/Cursos/Index.cshtml
@page
@model AplicacionNetRazor.Pages.Cursos.IndexModel
@{
    ViewData["Title"] = "Lista de cursos";
}

@if (Model.Mensaje != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      @Model.Mensaje
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
}

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-sm-6">
                <h2 class="text-info">Lista de cursos</h2>
            </div>
            <div class="col-sm-6">
                <a asp-page="Crear" class="btn btn-primary">Crear nuevo curso</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <form method="post">
        @if (Model.Cursos.Count() > 0)
        {
            <br /><br />
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>@Html.DisplayNameFor(m => m.Cursos.First().Id)</th>
                    <th>@Html.DisplayNameFor(m => m.Cursos.First().NombreCurso)</th>
                    <th>@Html.DisplayNameFor(m => m.Cursos.First().CantidadClases)</th>
                    <th>@Html.DisplayNameFor(m => m.Cursos.First().Precio)</th>
                    <th>@Html.DisplayNameFor(m => m.Cursos.First().FechaCreacion)</th>
                    <th>Acciones</th>
                </tr>
                @foreach (var item in Model.Cursos)
                {
                    <tr>
                        <td>@Html.DisplayFor(m => item.Id)</td>
                        <td>@Html.DisplayFor(m => item.NombreCurso)</td>
                        <td>@Html.DisplayFor(m => item.CantidadClases)</td>
                        <td>@Html.DisplayFor(m => item.Precio)</td>
                        <td>@Html.DisplayFor(m => item.FechaCreacion)</td>
                        <td>
                            <a asp-route-id="@item.Id" asp-page="Editar" class="btn btn-success btn-sm">Editar</a>
                            <button asp-page-handler="Borrar" asp-route-id="@item.Id" onclick="return confirm('Está seguro de querer borrar el curso?')" class="btn btn-danger btn-sm">Borrar</button>
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>No hay cursos disponibles</p>
        }
        </form>
    </div>
</div>